<!-- eslint-disable vue/first-attribute-linebreak -->
<!-- pages/items/new.vue -->
<template>
    <div class="">
        <h1 class="text-2xl font-semibold mb-6">Create New Item</h1>

        <UForm :state="form" @submit="handleSubmit">
            <div class="grid gap-7">
                <!-- Item name -->


                <UInput v-model="form.name" size="xl" placeholder="" :ui="{ base: 'peer' }">
                    <label
                        class="pointer-events-none absolute left-0 -top-2.5 text-(--ui-text-highlighted) text-xs font-medium px-1.5 transition-all peer-focus:-top-2.5 peer-focus:text-(--ui-text-highlighted) peer-focus:text-xs peer-focus:font-medium peer-placeholder-shown:text-sm peer-placeholder-shown:text-(--ui-text-dimmed) peer-placeholder-shown:top-1.5 peer-placeholder-shown:font-normal">
                        <span class="inline-flex bg-(--ui-bg) px-1">Item Name</span>
                    </label>
                </UInput>

                <!-- Unit type select -->
                <USelect v-model="form.unitType" :items="unitTypes" option-attribute="label" value-attribute="value"
                    label="Unit Type" placeholder="Select unit type" required size="xl" />

                <UInput v-model="form.rate" size="xl" placeholder="" :ui="{ base: 'peer' }">
                    <label
                        class="pointer-events-none absolute left-0 -top-2.5 text-(--ui-text-highlighted) text-xs font-medium px-1.5 transition-all peer-focus:-top-2.5 peer-focus:text-(--ui-text-highlighted) peer-focus:text-xs peer-focus:font-medium peer-placeholder-shown:text-sm peer-placeholder-shown:text-(--ui-text-dimmed) peer-placeholder-shown:top-1.5 peer-placeholder-shown:font-normal">
                        <span class="inline-flex bg-(--ui-bg) px-1">Rate</span>
                    </label>
                </UInput>

                <!-- Save button -->
                <UButton type="submit" class="mt-4">Save Item</UButton>
            </div>
        </UForm>

        <!-- Success alert -->
        <UAlert v-if="saved" color="primary" variant="subtle" class="mt-4">
            Item saved successfully!
        </UAlert>
    </div>
</template>

<script setup lang="ts">
    import { itemRepo } from '@/DataLayer/repositories/ItemRepository'
    import type { IItem, UnitType } from '@/DataLayer/types'

    definePageMeta({
        layout: 'default'
    })

    interface NewItem extends IItem { }

    const form = reactive<NewItem>({
        name: '',
        unitType: '' as UnitType,
        rate: 0,
    })

    const saved = ref(false)

    const unitTypes = ref([
        { label: 'Fixed', value: 'Fixed' },
        { label: 'Hourly', value: 'Hourly' },
    ])

    const handleSubmit = async () => {
        // Persist through the repository (returns autogenerated id)
        await itemRepo.add({ ...form })

        // reset form
        Object.assign(form, {
            name: '',
            unitType: '' as UnitType,
            rate: 0,
        })

        saved.value = true
        setTimeout(() => (saved.value = false), 3000)
    }
</script>

<style scoped></style>
