<!-- eslint-disable vue/first-attribute-linebreak -->
<template>
  <div class="max-w-2xl mx-auto p-6">
    <h1 class="text-2xl font-semibold mb-6">Create New Customer</h1>

    <UForm :state="form" @submit="handleSubmit">
      <div class="grid gap-4">
        <UInput v-model="form.name" label="Name" placeholder="John Doe" required />
        <UInput v-model="form.phone" label="Phone" placeholder="+1 555‑555‑5555" />
        <UInput v-model="form.email" label="Email" placeholder="john@example.com" type="email" />
        <UTextarea v-model="form.address" label="Address" placeholder="123 Main St, City, Country" />
        <UInput v-model="form.companyName" label="Company Name" placeholder="Acme Inc." />

        <!-- Image picker -->
        <div>
          <label class="block text-sm font-medium mb-1">Image</label>
          <input type="file" accept="image/*"
            class="file-input block w-full text-sm text-gray-700 file:mr-4 file:py-2 file:px-4 file:rounded file:border-0 file:text-sm file:font-semibold file:bg-primary-600 file:text-white hover:file:bg-primary-700;"
            @change="onFileChange">
          <img v-if="form.image" :src="form.image" alt="Preview" class="mt-2 h-24 w-24 object-cover rounded">
        </div>

        <!-- Currency select -->
        <!-- Currency select -->
        <USelect v-model="form.currency" :items="currencies" option-attribute="label" value-attribute="value"
          label="Currency" placeholder="Select currency" />

        <UButton type="submit" class="mt-4">Save Customer</UButton>
      </div>
    </UForm>

    <UAlert v-if="saved" color="primary" variant="subtle" class="mt-4">
      Customer saved successfully!
    </UAlert>
  </div>
</template>

<script setup lang="ts">
  import { customerRepo } from '@/DataLayer/repositories/CustomerRepository'; // adjust alias as needed
  import type { ICustomer } from '@/DataLayer/types';


  // Extend the base interface to include optional image data URI
  interface NewCustomer extends ICustomer {
    image?: string
  }

  const form = reactive<NewCustomer>({
    name: '',
    phone: '',
    email: '',
    address: '',
    companyName: '',
    image: '',
    currency: ''
  })

  const saved = ref(false)

  const currencies = ref([
    { label: 'US Dollar (USD)', value: 'USD' },
    { label: 'Euro (EUR)', value: 'EUR' },
    { label: 'British Pound (GBP)', value: 'GBP' },
    { label: 'Japanese Yen (JPY)', value: 'JPY' },
    { label: 'Pakistani Rupee (PKR)', value: 'PKR' },
    { label: 'Indian Rupee (INR)', value: 'INR' }
  ])

  const handleSubmit = async () => {
    // Persist through the repository (returns autogenerated id)
    await customerRepo.add({ ...form })

    // reset form
    Object.assign(form, {
      name: '',
      phone: '',
      email: '',
      address: '',
      companyName: '',
      image: '',
      currency: ''
    })

    saved.value = true
    setTimeout(() => (saved.value = false), 3000)
  }

  const onFileChange = (e: Event) => {
    const files = (e.target as HTMLInputElement).files
    if (files && files[0]) {
      const reader = new FileReader()
      reader.onload = (ev) => {
        form.image = ev.target?.result as string
      }
      reader.readAsDataURL(files[0])
    }
  }
</script>

<style scoped></style>
